geocodio/__init__.py,sha256=p-VopoBUhpnXOWjY7rj3C8X7v8EEx23iRIlHWNDwrJE,384
geocodio/client.py,sha256=kplRritMUxPneByHLUEMDKch1ssQbrqOUXZifKMQql0,8208
geocodio/data.py,sha256=POXPVvp3m41CVP7kXny5Mz7fR4zup6H7uIDV1p8inig,3997
geocodio/exceptions.py,sha256=ogv-rAfdiF2Pd4KbPyGpTcExuD0s2VJw6nrax2g4KV0,438
pygeocodio-0.9.0.dist-info/METADATA,sha256=ej67AqIGs-Kw-1mQzJkqoUvrL4NC9SqoqpJ30tZh5JE,6980
pygeocodio-0.9.0.dist-info/RECORD,,
pygeocodio-0.9.0.dist-info/WHEEL,sha256=NzFAKnL7g-U64xnS1s5e3mJnxKpOTeOtlXdFwS9yNXI,92
pygeocodio-0.9.0.dist-info/top_level.txt,sha256=mC-G7vXzLU9WCuQIA192zOi4k__HtnhAI--OvWSoMZs,9
