--- !ditz.rubyforge.org,2008-03-06/issue 
title: Bytes output if pygments is not installed
desc: |-
  When using python3 and pygments is not installed, if I run command pyditz
  todo, the output is something like:
  
      b'0.8.1 (unreleased):'
      b'_ {issue bba739003e93ad1d893c676ce2e67e408ad1778e}: HTML plugin load failure (bug)'
      ...
type: :bugfix
component: PyDitz
release: "0.9"
reporter: Timo Kankare <timo.kankare@iki.fi>
status: :closed
disposition: :fixed
creation_time: 2015-03-28 22:50:43.443367 Z
references: []

id: a776d5f55a04735eaa32c4c4fe190b901106fe20
log_events: 
- - 2015-03-28 22:50:43.445153 Z
  - Timo Kankare <timo.kankare@iki.fi>
  - created
  - ""
- - 2015-03-28 23:09:29.926141 Z
  - Timo Kankare <timo.kankare@iki.fi>
  - commented
  - |-
    It seems that in ditz/command.py write method encodes
    line to utf-8 bytes. If pygment is not installed those
    bytes are directly printed.
    
    Removing the encoding there seems to fix this bug.
- - 2015-04-01 21:05:19.147541 Z
  - Glenn Hutchings <zondo42@gmail.com>
  - assigned to release 0.9 from unassigned
  - |-
    Yes, removing the encoding fixes things.  Not sure why I put it in
    there now -- probably a hangover from trying to fix up unicode support.
    Let's include this in the next release.
- - 2015-04-01 21:05:43.922926 Z
  - Glenn Hutchings <zondo42@gmail.com>
  - closed with disposition fixed
  - ""
- - 2015-04-22 13:07:10.955000 Z
  - Glenn Hutchings <zondo42@gmail.com>
  - commented
  - |-
    Haha, not that simple.  Now causes an encoding error when showing
    the issue in an emacs buffer.  Fixed (again) by only doing the encoding
    in python 2.x.
