--- !ditz.rubyforge.org,2008-03-06/issue 
title: Initialization command doesn't work
desc: |-
  The `init` command either does nothing (if database already exists)
  or gives an error if it doesn't.
type: :bugfix
component: PyDitz
release: "0.9"
reporter: Timo Kankare <timo.kankare@iki.fi>
status: :closed
disposition: :fixed
creation_time: 2015-04-06 11:25:57.916600 Z
references: []

id: 1f7179add1b140bf3ba229ebb3e14fbaecba8c52
log_events: 
- - 2015-04-06 11:25:57.923377 Z
  - Glenn Hutchings <zondo42@gmail.com>
  - created
  - ""
- - 2015-04-06 11:27:03.356826 Z
  - Glenn Hutchings <zondo42@gmail.com>
  - closed with disposition fixed
  - |-
    In fact, `init` is now a no-op, since the database is automatically
    initialized if necessary.  Now marked as such.
